### PR TITLE
Add referer to fields

### PR DESCRIPTION
**Pull request by omid**
Add [http referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) to the fields

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
This is not part of [OpenTelemetry's HTTP semantic conventions](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/).
The proper field name should be `http.request.header.referer`, but I don't see a reason to add it among the default fields.

**Comment by omid** [comment]
@LukeMathWalker, Is there a specfic way to add custom fields next to the default fields?

**Comment by LukeMathWalker** [comment]
Yes, via [`root_span!`](https://docs.rs/tracing-actix-web/latest/tracing_actix_web/macro.root_span.html)

**Comment by omid** [comment]
@LukeMathWalker thanks. It helped a lot. I was not aware of the convention.

Out of curiosity, why `user_agent.original`, based on [otel semantic conventions](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/) named `http.user_agent` in the library?

**Comment by LukeMathWalker** [comment]
Historical mistakes we now have to live with—changing the field names now would be quite dangerous (e.g. folks are probably relying on them for alerts).

**Pull request closed without merging**
