### PR TITLE
Dependency bump and update examples

### PR DESCRIPTION
**Pull request by caizixian**

### CODE REVIEW

**Comment by james7132** [comment]
Please do merge this in sooner rather than later. The version bump in actix-web's dependencies is causing a compilation failure and this is the main blocker for users of the beta version of this crate.

**Comment by LukeMathWalker** [comment]
This has been addressed in #57.
I appreciate the PR @caizixian, but for the future: we want to use the lowest possible version for each of our dependencies; if you are submitting a PR for bumping up `actix-web`, avoiding requiring the latest of all other crates - this is actively harmful for dependency resolution of the users of our crate. We should only require a certain patch/minor version if we have a reason to do so - e.g. a bug fix. The current situation in `tracing-actix-web` is not perfect, we should indeed review the existing ranges to minimise them where possible.

@james7132 - you could have used the `patch` syntax to rely on this branch if that's what you need, see https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section
I merge PRs/do changes when I have the time - which might mean in a few weeks or months from time to time 😁

**Comment by james7132** [comment]
While I generally agree that patching is a workable workaround, anyone adding `tracing-actix-web` right now gets a broken build by default, and while sort of expected given that it's in beta, it's still a very poor developer experience for everyone involved, particularly since it isn't documented.

**Comment by neslinesli93** [comment]
Same here - for now I've fixed using @caizixian branch in my projects, but it really is less than optimal... I think this patch configures as a bug fix: the main dependency, actix beta 11, does not seem to compile at all

**Comment by LukeMathWalker** [comment]
If you pin `actix-web` to beta.11 and `tracing-actix-web` to 0.5.0-beta.2 your project will compile.

**Comment by neslinesli93** [comment]
> If you pinned `actix-web` to beta.11 and `tracing-actix-web` to 0.5.0-beta.2 your project would have compiled @neslinesli93.

I'll try, thank you :)

**Comment by LukeMathWalker** [comment]
It seems you need to pin `actix-http`, but that has nothing to do with this crate :)

**Pull request closed without merging**
