### PR TITLE
Update to actix-web 4.0.0-beta.4

### PR DESCRIPTION
**Pull request by vtavernier**

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
Happy to merge, although this is not strictly necessary - if you run `cargo update` on your project it will automatically pick up the latest `actix-web` beta release.

**Comment by LukeMathWalker** [comment]
It seems you opened the PR against a branch instead of `main`. I'll update `main` directly.

**Comment by vtavernier** [comment]
Yes for some reason I hadn't realized I didn't run `cargo update` and wondering why I had version conflicts. I initially made it against the `main` branch but it seemed the `actix-4-beta3` branch was more up to date (since it had the  `3.0.0-beta.2` released on crates.io).

**Comment by LukeMathWalker** [comment]
You're right, made a mistake there 😅

**Pull request merged**
