### PR TITLE
Updated actix-web dependency to `4.0.0-beta.15`

### PR DESCRIPTION
**Pull request by ondra05**

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
Thank you!

**Comment by chriskyndrid** [comment]
Cargo is still complaining about the .14 dependency. I see the update landed, but, can you increment to beta.6 in Cargo.toml?

**Comment by LukeMathWalker** [comment]
I can't cut a release from my phone 😄
It'll happen today.

**Comment by chriskyndrid** [comment]
No worries, it's resolved locally on my end, and thank you for the excellent work on tracing-actix-web. 

Have a wonderful weekend.

**Pull request merged**
