### PR TITLE
Add span prop as span generator config

### PR DESCRIPTION
**Pull request by lsunsi**
### Intention

The intention of this change is simple: letting
the user of the library configure the span
creation. This would be interesting, because
it'd let the user change the field names
and even add more fields without disrupting
the lib.

### Easy of use consideration

The Default trait allows for people that do not
care about this customization to leverage the sane
defaults as it were before, so I think it's win win.

### Concerns

This change is kind of intense in complexity because it
adds the requirement of static function definition. I wanted to
avoid this "power requirement" passing some configs, but
reading the tracing and tracing core libraries I got the impression
that trace macros are kind of hard to call with dynamic args.
Am I missing something in this subject?

### Features

Of course with this level o customization power, this PR takes
some weights from this libraries back. For example, #5 #6 and #11 
could all be solved by creating a custom span function.

Further, I want to have a "enduser.id" field on the span for my
current application and I would be able to add it as well, which
means users could add custom fields for example.

### Thanks

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
> ### Concerns
> 
> This change is kind of intense in complexity because it
> adds the requirement of static function definition. I wanted to
> avoid this "power requirement" passing some configs, but
> reading the tracing and tracing core libraries I got the impression
> that trace macros are kind of hard to call with dynamic args.
> Am I missing something in this subject?

That's unfortunately the case - macros no do compose particularly well.
The issue I see, with this change, is that you are only allowing the user of the library to customize span creation - you are not giving them a chance to register fields after the request has completed.
E.g. there is a call to `span.record` with a hard-coded `status_code` as field name. As a user, I have no way to actually capture the status code in another field if I want to.

**Comment by lsunsi** [comment]
@LukeMathWalker You are right! I went over my head. It really makes this option difficult without more changes, like adding also an `update_span` function. Do you have any ideas on how to make this more simply? If you think the `new_span/update_span` configuration functions make sense I can take a crack at it, but I'm worried it might not align with the purposes of this lib.

**Comment by LukeMathWalker** [comment]
> @LukeMathWalker You are right! I went over my head. It really makes this option difficult without more changes, like adding also an `update_span` function. Do you have any ideas on how to make this more simply? If you think the `new_span/update_span` configuration functions make sense I can take a crack at it, but I'm worried it might not align with the purposes of this lib.

I think it's worth exploring the space - it would be great to land on a solution that allows people to inject the right level of customisation without having to copy-paste the code from this library in their own projects just to add/rename/tweak a few minor details.

If you ask for my opinion, we probably want some kind of trait with two methods attached - one to create the span, one to record fields on the span when the request completes. We can then provide a vanilla implementation while allowing customisation.

**Comment by lsunsi** [comment]
@LukeMathWalker Awesome, you have the same opinion as me. (: I pushed a new commit adding the 'update_span' function that would give the user the power to create and update the span. I'll try to add them to a trait so they user can pass an object instead of bare functions, but I already works as is I think. What do you think?

**Comment by LukeMathWalker** [comment]
We are getting closer 😁 
I still think we want a trait though, ideally with asynchronous methods - using free functions there is no way to persist any state between the creation of the span and its population later on.
This makes it impossible, for example, to use a timer - where do you stash it?

What issue did you encounter when trying with a trait?

**Comment by LukeMathWalker** [comment]
I have included a mechanism for users to customise the root span in `0.4.0-beta.1` - please check it out and let me know what do you think @lsunsi!

**Pull request closed without merging**
